name: publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  publish:
    if: ${{ github.repository_owner == 'minori-ty' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: check version
        uses: EndBug/version-check@v2  # 当package.json version发生变化时，才会重新打包
        id: check

      - name: set version
        id: version
        run: |
          echo "MY_VERSION=${{ steps.check.outputs.version }}" >> $GITHUB_ENV
          echo "------------------------------"
          echo "version is ${{ steps.check.outputs.version }}"
          echo "------------------------------"

      - name: Build & publish
        # if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
            node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: push
        if: steps.check.outputs.changed == 'true'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
