name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 缓存 node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装依赖
        run: |
          npm i

  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4

      - name: 缓存 gradle
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装依赖
        run: |
          npm i

      - name: 启动java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 打包安卓
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release/

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v0.0.7
          tag_name: v0.0.7
          files: android/app/build/outputs/apk/release/app-release.apk
